from .aulas import Aula
from .carreras import Carreras
from .coordinadores import Coordinadores
from .edificios import Edificios
from .enums import TurnoEnum
from .enums import StatusEnum
from .materias import Materias
from .materias_propuestas import Materias_Propuestas
from .estudiante import Estudiante
from .docentes import Docente